theme: jekyll-theme-minimal
title: Lightning Shell
description: "Your personal server's shell"

url: "https://lightningshell.app/"
baseurl: ""

github:
  repository_url: https://github.com/ibz/lightning-shell
  repository_nwo: ibz/lightning-shell

author:
  name: Ioan Bizău
  url: https://ibz.me
  email: lnsh@ibz.me

plugins:
  - jekyll-redirect-from

permalink: /posts/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
